wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import os

import flask
from flask import Blueprint, current_app, Response, jsonify, make_response
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user
from werkzeug.utils import secure_filename
import pdfkit

from wiki.core import Processor
from wiki.web.forms import EditorForm, ChangePasswordForm, UserEditorForm, RegisterForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki, get_users, get_pictures
from wiki.web import current_users
from wiki.web.user import protect, admin_protect
from users import UserManager, User, Users

bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    images = get_pictures()
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page, images=images)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.login_user(form.name.data, form.password.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/register/', methods=['GET', 'POST'])
def user_register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        email_address = register_form.email.data
        # check database for same email
        email_exist = Users.email_used(email_address)
        if email_exist is True:
            flash('That email is already in use. Use another one', 'fail')
            return render_template('register.html', form=register_form)

        if email_exist is False:
            # add user to database
            Users.register_user(register_form.name.data,
                                register_form.password.data,
                                email_address)
            flash('Account Registration was a success', 'success')
            return render_template('login.html', form=register_form)

    return render_template('register.html', form=register_form)


@bp.route('/user/change_password/', methods=['GET', 'POST'])
def user_change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.set_password(form.confirm_password.data)
        current_user.set('authenticated', True)
        flash('Password Change Successful.', 'success')
        return render_template('change_password.html', form=form)
    return render_template('change_password.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.user_login'))


@bp.route('/user/create/', methods=['GET', 'POST'])
def user_create():
    form = UserEditorForm()
    if form.validate_on_submit():
        current_users.add_user(form.name.data, form.password.data, form.active.data)
        return redirect(url_for('wiki.admin'))
    return render_template('User/addEdit.html', form=form, create=True)


@bp.route('/user/edit/<int:user_id>/', methods=['GET', 'POST'])
def user_edit(user_id):
    user_manager = get_users()
    user = user_manager.get_user(user_id)
    form = UserEditorForm(name=user.get("name"), password=user.get("password"), active=user.get("active"))

    if form.validate_on_submit():
        user.set("name", form.name.data)
        user.set("password", form.password.data)
        user.set("active", form.active.data)
        user.save()

        return redirect(url_for('wiki.admin'))
    return render_template('User/addEdit.html', form=form, create=False)


@bp.route('/user/delete/<string:user_id>/')
def user_delete(user_id):
    get_users().delete_user(user_id)
    return redirect(url_for('wiki.admin'))


@bp.route('/user/delete/<string:user_id>/')
def user_self_delete(user_id):
    get_users().delete_user(user_id)
    return redirect(url_for('wiki.login'))


@bp.route('/admin/')
@admin_protect
def admin():
    users = current_users
    return render_template('admin.html', users=users.read())


@bp.route('/profile/')
def profile():
    users = current_users
    return render_template('profile.html', users=users.read())


@bp.route('/ajax/pictures/', methods=['POST', 'GET'])
def ajax_pictures():
    if request.method == "GET":
        images = get_pictures()
        return render_template('pictures.html', images=images)
    elif request.method == "POST":
        file = request.files['file']
        filename = secure_filename(file.filename)
        path = os.path.join(current_app.config['PIC_BASE'], filename)

        # if the filename already exists, come up with a new filename
        # that is the old filename with a number added to the end
        # ex: if pic.gif already exists, then save as pic1.gif
        if os.path.exists(os.path.join(current_app.config['PIC_BASE'], filename)):
            count = 1
            new_name = filename
            while os.path.exists(os.path.join(current_app.config['PIC_BASE'], new_name)):
                split_name = filename.rsplit('.', 1)
                name = split_name[0] + str(count)
                extension = split_name[1]
                new_name = name + '.' + extension
                count += 1
            filename = new_name

        if file:
            file.save(os.path.join(current_app.config['PIC_BASE'], filename))
        else:
            resp = jsonify({'message': 'Error in file'})
            resp.status_code = 400

        resp = jsonify({'message': 'success', 'filename': filename})
        resp.status_code = 201
        return resp


@bp.route('/export/<path:url>/', methods=['GET', 'POST'])
@protect
def export(url):
    page = current_wiki.get_or_404(url)

    form = URLForm(obj=page)
    if request.method == 'POST':
        if request.form['submit_button'] == 'PDF':
            html = page.html
            base_url = flask.request.host_url
            rendered = render_template('pdf_page_template.html', page=page, base_url=base_url)
            pdf = pdfkit.from_string(rendered, False)

            response = make_response(pdf)
            response.headers['Content-Type'] = 'application/pdf'
            response.headers['Content-Disposition'] = 'inline; filename={}.pdf'.format('Test')

            return response
        else:
            pass

    return render_template('export.html', form=form, page=page)


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/admin.html
{% extends "base.html" %}

{% block title %}Admin Page{% endblock title %}

{% block content %}
    <h1>User Management</h1>
    <table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>Authenticated</th>
        <th>Active</th>
        <th></th>
        <th></th>
    </tr>
    {% for user in users %}
        <tr>
            <td>
                {{ user.get("name") }}
            </td>
            <td>
                {{ user.get("authenticated")  }}
            </td>
            <td>
                {{ user.get("active") }}
            </td>
            <td>
                <a href="{{ url_for('wiki.user_edit', user_id=user.id) }}" class="btn btn-sm btn-secondary">Edit</a>
            </td>
            <td>
                <a href="{{ url_for('wiki.user_delete', user_id=user.id) }}" class="text-info">X</a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock content %}

{% block sidebar %}
    <div class="text-center">
        <a href="{{ url_for('wiki.user_create') }}" class="btn btn-primary btn-large">New User</a>
    </div>
{% endblock sidebar %}

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand">{{ config.TITLE }}</a>
							<ul class="nav">
								<li><a href="{{ url_for('wiki.home') }}">Home</a></li>
								<li><a href="{{ url_for('wiki.index') }}">Index</a></li>
								<li><a href="{{ url_for('wiki.tags') }}">Tags</a></li>
								<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
								{% if current_user.is_authenticated %}
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            Welcome, {{ current_user.get("name") }}! <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{{ url_for('wiki.profile') }}">Profile</a></li>
                                            {% if current_user.has_role('admin') %}
                                                <li><a href="{{ url_for('wiki.admin') }}">Admin</a></li>
                                            {% endif %}
                                            <li><a href="{{ url_for('wiki.user_change_password') }}">Change Password</a></li>
                                            <li><a href="{{ url_for('wiki.user_logout') }}">Logout</a></li>
                                        </ul>
                                      </li>
								{% else %}
									<li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
                                    <li><a href="{{ url_for('wiki.user_register') }}">Register</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/export.html
{% extends "base.html" %}

{% block title %}Export a page{% endblock title %}
{% block content %}
<h3>Supported Export Options:</h3>
<form method="POST" class="form-inline">
    <input type="submit" name="submit_button" value="PDF"/>
</form>
{% endblock content %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
    <div class="control-group {% if field.errors %}error{% endif %}">
        {% if field.type == 'BooleanField' %}
            <div class="controls">
                <label for="{{ field.name }}" class="checkbox">
                    {{ field(**kwargs) }}
                    {{ field.label.text }}
                </label>
            </div>
        {% else %}
            <label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
            <div class="controls">
                {{ field(**kwargs) }}
                {% if field.errors %}
                    <div>
                        {% for error in field.errors %}
                            <span class="help-inline">
								{{ error }}
							</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endif %}
    </div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
	{{ page.title }}
{% endblock title %}

{% block content %}
  <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
      <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
      <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
    </div>
  </div>
	{{ page }}
{% endblock content %}

{% block sidebar %}
{% if page.tags %}
<h3>Tags</h3>
  <ul>
      {% for tag in page.tags.split(',') %}
        <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}
<h3>Actions</h3>
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
  <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
    <li><a href="{{ url_for('wiki.export', url=page.url) }}">Export</a></li>
  <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/pdf_page_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page.title }}</title>
    <base href="{{ base_url }}">

    <h1>Riki Wiki - {{ page.title }}</h1>
    <style type="text/css">
      .container {
        max-width: 500px;
        padding-top: 100px;
      }
    </style>
  </head>
  <body>
    <p>{{ page }}</p>
  </body>
  <br>
  <br>
  <div class="footer">
    {% block footer %}
        <p>Tags: {{ page.tags }}</p>
      {% endblock %}
  </div>
</html>

wiki/web/templates/pictures.html
<div class="gallery img-selector">
    {% for image in images %}
        <div class="mb-3 pics animation all 2">
            <img src="{{ url_for('static', filename=('images/'+image)) }}" class="img-fluid img-polaroid"/>
        </div>
    {% endfor %}
</div>

wiki/web/templates/profile.html
{% extends "base.html" %}

{% block title %}Profile Page{% endblock title %}

{% block content %}
    <h1>Profile Management</h1>
    <table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>Authenticated</th>
        <th>Active</th>
    </tr>
        <tr>
            <td>
                {{ current_user.get("name") }}
            </td>
            <td>
                {{ current_user.data.get('authenticated') }}
            </td>
            <td>
                {{ current_user.data.get('active') }}
            </td>
        </tr>
    </table>
{% endblock content %}

{% block sidebar %}
    <div class="text-center">
        <a href="{{ url_for('wiki.user_change_password') }}" class="btn btn-primary btn-large">Change Password</a>
        <a href="{{ url_for('wiki.user_self_delete', user_id=current_user) }}" class="btn btn-primary btn-large">Delete Account</a>
    </div>
{% endblock sidebar %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}